[package]
name = "myroute-osm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bincode.workspace = true
myroute-core = { path = "../myroute-core" }
osmpbfreader.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
protobuf.workspace = true
tempfile.workspace = true
