[package]
name = "myroute-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "myroute"
path = "src/main.rs"

[dependencies]
clap.workspace = true
myroute-core = { path = "../myroute-core" }
myroute-osm = { path = "../myroute-osm" }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
osmpbfreader.workspace = true
protobuf.workspace = true
tempfile.workspace = true
